### ISSUE TITLE
env var HOOK_DISABLE_TRACE not working correctly

### ISSUE THREAD

**Issue by dynamicheart** [lipracer/cuda-rt-hook#137]
# Description

Environment Variables: 
`HOOK_DISABLE_TRACE='xpuSetDevice=0' LOG_LEVEL="TRACE=INFO"`

Desired Behavior:
only `xpu_set_device` is backtraced

Actual Behavior:
all runtime apis are backtraced

<img width="1137" alt="image" src="https://github.com/lipracer/cuda-rt-hook/assets/19570241/5aa4e187-18a6-4c1e-8ef3-43156b4c57af">

<img width="1723" alt="2d2efd2360cb35b22bc257ea003d6b42" src="https://github.com/lipracer/cuda-rt-hook/assets/19570241/96711936-f27b-4061-bc79-7fd9eeb7a73d">

**Comment by lipracer** [comment]
https://github.com/lipracer/cuda-rt-hook/blob/705449fe8f5234f43364e495f55a8bd3b263d684/include/backtrace.h#L21 default: `return true`?

**Comment by dynamicheart** [comment]
> https://github.com/lipracer/cuda-rt-hook/blob/705449fe8f5234f43364e495f55a8bd3b263d684/include/backtrace.h#L21
> 
> default: `return true`?

Yes

**Comment by lipracer** [comment]
https://github.com/lipracer/cuda-rt-hook/commit/9bdd23eb76e0ea153b21ac794f14f0917e8b841c Fixed
